### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by terrencetec** [jkh675/hkfws_timer_app#2]
https://github.com/jkh675/hkfws_timer_app/blob/0fffd4bb91ad918aaf338e3a5f016879a496cea9/src/App.tsx#L83-L117

Perhaps separate the styling portion in a separate file and have the main file import it.

P.S. My green is #00FF66 (Or #00FFAA if you prefer a lighter font.)

Future work:

1. Make options to change the style and fonts.
2. Make sizes dynamically fit the screen according to the screen resolution.

**Comment by jkh675** [comment]
the font size and button size is already scaled by the screen size it depends on your device's DPI

**Comment by jkh675** [comment]
Color changed
